(TeX-add-style-hook "dissertation"
 (lambda ()
    (LaTeX-add-bibliographies)
    (LaTeX-add-environments
     "Theorem"
     "Algorithm"
     "assume")
    (LaTeX-add-labels
     "fig:2F43"
     "ECAssume"
     "ass:expcorr"
     "ass:isozyme"
     "ass:hierarchy"
     "ass:nostoich"
     "ass:sharing"
     "ass:holo"
     "alg:ReductionToCNF"
     "thm:ReductionToCNF"
     "alg:eMoMA")
    (TeX-add-symbols
     "ifpdf")
    (TeX-run-style-hooks
     "palatino"
     "txfonts"
     "hangcaption"
     "epsfig"
     "subfigure"
     "moreverb"
     "graphics"
     "pstricks"
     "graphicx"
     "ntheorem"
     "thmmarks"
     "amsthm"
     "algorithmic"
     "tikz"
     "float"
     "hyperref"
     "amsmath"
     "soul"
     ""
     "latex2e"
     "cornell10"
     "cornell"
     "tocprelim"
     "phd")))

